//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBookvie
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        [ScaffoldColumn(false)]
        public int lib_id { get; set; }
        [Display(Name = "Categoría")]
        [Required(ErrorMessage = "La categoría es requerida")]
        public int cat_id { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El titulo es requerido"), MaxLength(55)]
        [Display(Name = "Nombre")]
        public string lib_tit { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Autor(es) es requerido"), MaxLength(55)]
        [Display(Name = "Autor(es) ej: Autor 1, Autor 2")]
        public string lib_aut { get; set; }
        [Display(Name = "Fecha")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime lib_fpb { get; set; }
        [Display(Name = "Número de Ejemplares")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        public int lib_nej { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
