//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBookvie
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video
    {
        [ScaffoldColumn(false)]
        public int vid_id { get; set; }
        [Display(Name = "Categoría")]
        [Required(ErrorMessage = "La categoría es requerida")]
        public int cat_id { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El título es requeridos"), MaxLength(55)]
        [Display(Name = "Titulo")]
        public string vid_tit { get; set; }
        [Display(Name = "Fecha")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public System.DateTime vid_fpb { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El formato es requeridos"), MaxLength(55)]
        [Display(Name = "Formato")]
        public string vid_frm { get; set; }
        [Display(Name = "Duración")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "Solo se permiten números")]
        public int vid_dur { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
